name: sqliteraw.dart
description: SQLite raw Dart ffi, no alterations, so that you can use the full SQLite C API
version: 0.0.1-3510100
repository: https://github.com/TarasMazepa/sqliteraw.dart

environment:
  sdk: ^3.7.1

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^17.0.0
  lints: ^5.0.0
  test: ^1.24.0

ffigen:
  output: 'lib/sqliteraw.dart'
  headers:
    entry-points:
      - '../sqlite/sqlite3.h'
